---
name: Gradle

on:
  push:
  pull_request:

jobs:
  build:
    strategy:
      matrix:
        java: [11, 17]
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    env:
      gradle_commands: --stacktrace build
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK ${{ matrix.java }}
        uses: actions/setup-java@v3
        with:
          java-version: ${{ matrix.java }}
          distribution: 'zulu'
      - name: Run commands
        run: |
          ./gradlew ${{ env.gradle_commands }}
      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: omeropcsteward
          path: build/libs/*.zip
          if-no-files-found: error
