---
name: Gradle

on:
  push:
  pull_request:

jobs:
  build:
    strategy:
      matrix:
        java: [11, 17]
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    env:
      gradle_commands: --stacktrace build
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK ${{ matrix.java }}
        uses: actions/setup-java@v3
        with:
          java-version: ${{ matrix.java }}
          distribution: 'zulu'
      - name: Build
        run: |
          ./gradlew ${{ env.gradle_commands }}
      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: omero-pc-steward
          path: build/libs/*.jar
          if-no-files-found: error
  upload:
    name: Create release
    needs: build
    runs-on: ubuntu-latest
    if: startswith(github.ref, 'refs/tags/')
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v3
      - name: List artifacts
        run: ls -R
      - name: Create release draft
        uses: softprops/action-gh-release@v1
        with:
          files: |
            omero-pc-steward/*.jar
          draft: true
          fail_on_unmatched_files: true
